name: amira_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  persistent_bottom_nav_bar_v2: ^5.2.3
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.5.0
  extended_image: ^8.2.1
  intl: ^0.19.0
  flutter_localizations:
     sdk: flutter
  flutter_phoenix: ^1.1.1
  lottie: ^3.1.2
  carousel_slider: ^4.2.1
  firebase_core_platform_interface: ^5.2.1
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  permission_handler: ^11.0.1
  awesome_notifications: ^0.9.3+1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/images/
      - assets/products/
      - assets/animation/
      - assets/lang/ru.json
      - assets/lang/tr.json
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/PeaceSans.ttf